#!/usr/bin/env bash
# Install and configure HAproxy 
sudo apt-get update
sudo apt-get install haproxy -y 

# Configure loadbalancer
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend myfrontend bind *:80 default_backend myserversbackend myservers 
balance roundrobin server web-01 your IP address:80 check server web-02 your Ip addre80 checkEOT # start the loadbalancersudo /etc/init.d/haproxy start # set HAProxy to start at bootsudo update-rc.d haproxy defaults # reload HAProxy configurations
