#!/usr/bin/env bash
# Configures and starts a new Nginx server so that /redirect_me is redirecting to another page.
# The redirection file must be a “301 Moved Permanently”.

sudo apt-get update -y
sudo apt-get install nginx -y

# This leads to the Redirection Page
sudo sed -i '/server_name _;/a \\t location /redirect_me {\n\t\t return 301  https://www.youtube.com/watch?v=rv7uzsBm8zw;\n\t}' /etc/nginx/sites-available/default

# This is the Reload nginx configuration
sudo service nginx restart
