#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
# Enables management via the init script.
# Distributes requests using a round-robin algorithm
# Updating the package list

# To install the HAProxy inside my lb server
sudo apt-get install -y haproxy

# To update the HAProxy configuration file to configure it with my two servers
sudo tee /etc/haproxy/haproxy.cfg > /dev/null << EOF
frontend http_front
    bind *:80
    default_backend http_back
backend http_back
    balance roundrobin
    server web-01 34.224.63.228 check
    server web-02 54.225.241.72:80 check
EOF
# start the load balancer with init
sudo /etc/init.d/haproxy start

# set HAProxy to start at boot
sudo update-rc.d haproxy defaults

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
