#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations
# Enables management via the init script and distributes the requests using a round-robin algorithm
# Updating the package 

sudo apt-get update
sudo apt-get install haproxy -y

# Configure loadbalancer
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend myfrontend
        bind *:80
        default_backend myservers
backend myservers
        balance roundrobin
        server web-01 34.224.63.228:80 check
        server web-02 54.225.241.72:80 check
EOT

# start the loadbalancer
sudo /etc/init.d/haproxy start

# set HAProxy to start at boot
sudo update-rc.d haproxy defaults

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
