#!/usr/bin/env bash
# Script to download the nginx
sudo apt-get update
sudo apt-get install nginx -y

# #!/usr/bin/env bash
# The Script to download nginx
sudo apt-get update
sudo apt-get install nginx -y

# The Script to create my hello world page
echo "Hello World!" | sudo tee /var/www/html/index.html

# The Script to create a redirection to my website
sudo sed -i '/server_name _;/a \  location /redirect_me {\n    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n  }' /etc/nginx/sites-available/default

# The Script to create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# The Script to configure my custom page
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }' /etc/nginx/sites-available/default

# The Script to create custom header to my website
sudo sed -i "/^http {/a \    add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# The Script to restart my server
sudo service nginx restart
