#!/usr/bin/env bash
# This script is to fix Ubuntu container to be able to listen on port 80
# Also to debug nginx port 80

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
