#!/usr/bin/env bash                                                             
#This script is used to start apache2 inside docker                                                     
service apache2 start
